### ISSUE TITLE
Unreached code, and bzip2.patch out of date.

### ISSUE THREAD

**Issue by demerphq** [pmqs/Compress-Raw-Bzip2#10]
On HPUX this module throws build warnings:

```
"bzlib.c", line 862: warning #2111-D: statement is unreachable
     AssertH ( 0, 6001 );
"compress.c", line 261: warning #2549-D: variable "nBytes" is used before its
          value is set
     ((void)nBytes); /* Silence variable ‘nBytes’ set but not used warning */
```

Reviewing the code both are correct. 

For the bzlib.c case the function BZ2_bzDecompress has a while(1) look with no breaks inside, all exits from the loop are via a return statement. Presumably the AssertH() is there to detect if somehow that changes, but for a picky compiler it throws warnings. 

For the compress.c case the functions reads from nBytes before it is set.

```
$ git diff
diff --git a/bzip2-src/bzlib.c b/bzip2-src/bzlib.c
index 88118bf..e870307 100644
--- a/bzip2-src/bzlib.c
+++ b/bzip2-src/bzlib.c
@@ -859,9 +859,7 @@ int BZ_API(BZ2_bzDecompress) ( bz_stream *strm )
       }
    }
 
-   AssertH ( 0, 6001 );
-
-   return 0;  /*NOTREACHED*/
+   /*NOTREACHED*/
 }
 
 
diff --git a/bzip2-src/compress.c b/bzip2-src/compress.c
index 99cd709..a43ec65 100644
--- a/bzip2-src/compress.c
+++ b/bzip2-src/compress.c
@@ -240,7 +240,8 @@ void sendMTFValues ( EState* s )
 {
    Int32 v, t, i, j, gs, ge, totc, bt, bc, iter;
    Int32 nSelectors, alphaSize, minLen, maxLen, selCtr;
-   Int32 nGroups, nBytes;
+   Int32 nGroups;
+   Int32 nBytes = 0;
 
    /*--
    UChar  len [BZ_N_GROUPS][BZ_MAX_ALPHA_SIZE];

```

I wanted to apply these two patches, and the send you the diff along with an updated bzip2.patch file as well, but i cannot apply the bzip2.patch file to reverse out the existing changes.  It looks like the bzip2.patch file was produced a long time ago, and since then various updates have been made to the distributed code without updating the patch file. Also two of the files the .patch file references aren't in the distributed code.

```
$ patch -R -p1 < bzip2.patch 
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/bzip2.c b/bzip2.c
|index d95d280..7852cc4 100644
|--- a/bzip2.c
|+++ b/bzip2.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 22
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/bzip2recover.c b/bzip2recover.c
|index a8131e0..0925048 100644
|--- a/bzip2recover.c
|+++ b/bzip2recover.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
2 out of 2 hunks ignored
patching file bzlib.c
Hunk #1 succeeded at 169 (offset 4 lines).
Hunk #2 succeeded at 178 (offset 4 lines).
Hunk #3 FAILED at 362.
Hunk #4 succeeded at 413 (offset 4 lines).
Hunk #5 succeeded at 473 (offset 4 lines).
Hunk #6 succeeded at 509 (offset 4 lines).
Hunk #7 succeeded at 688 (offset 4 lines).
Hunk #8 succeeded at 814 (offset 4 lines).
Hunk #9 succeeded at 867 (offset 4 lines).
Hunk #10 succeeded at 938 (offset 4 lines).
Hunk #11 succeeded at 986 (offset 4 lines).
Hunk #12 FAILED at 1107.
Hunk #13 succeeded at 1183 (offset 4 lines).
2 out of 13 hunks FAILED -- saving rejects to file bzlib.c.rej
patching file bzlib_private.h
patching file crctable.c
patching file decompress.c
Hunk #1 FAILED at 209.
1 out of 1 hunk FAILED -- saving rejects to file decompress.c.rej
patching file randtable.c
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file randtable.c.rej
```

Please let me know what i can do to tell help you help me silence the HPUX warnings. I am on a warpath to get perl to build warning clean on HPUX itanium. Thanks in advance!

**Comment by pmqs** [comment]
Thanks Yves

I'm usually cautious about applying changes to upstream code, but these looks very straightforward, so I've applied them.

Will see if I can push the changes upstream

**Comment by demerphq** [comment]
> I'm usually cautious about applying changes to upstream code, but these looks very straightforward, so I've applied them.

Yeah, I know, and I understand, and i would feel the same way myself. :-)

FWIW, one of my main concerns was that I couldn't reverse apply the .patch file anymore. I wanted to apply it in reverse, and then produce a replacement including the changes I did, but I couldn't go back.
