### ISSUE TITLE
change in build behaviour from 2.207

### ISSUE THREAD

**Issue by dakkar** [pmqs/Compress-Raw-Bzip2#14]
before 5c062e721de5f13782e15b9f6f35c98332e4e15d the default was to build the embedded bzip2 library

after that commit, the default is to _not_ build it

therefore, machines that don't have a `bzlib.h` header already present (and the accompanying library), can't build this distribution anymore

was that change intentional? the README seems to imply it was an accident, and maybe `getBoolean` should return 1 when the env variable is not present

**Comment by pmqs** [comment]
Hey @dakkar 

Good catch! No, it certainly wasn't intentional. I'll sort it now.

**Comment by pmqs** [comment]
2.209 just uploaded to CPAN & GH
