### ISSUE TITLE
Missing entry in Changes for 2.095

### ISSUE THREAD

**Issue by perlpunk** [pmqs/Compress-Raw-Bzip2#3]
https://metacpan.org/source/PMQS/Compress-Raw-Bzip2-2.095/Changes

**Comment by pmqs** [comment]
Thanks @perlpunk 

The CPAN copy is slightly out of sync with the GitHub copy. Should be fixed automatically in the next release.

The only change in 2.095 for this module was a version increment. No function changes were made.
